name: BlueArchiveEffect
version: '1.0.0'
main: me.axiumyu.blueArchiveEffect.BlueArchiveEffect
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:2.3.0'
api-version: '1.21'
depend:
  - packetevents
permissions:
  batype.use:
    description: 允许查看属性
    default: true
  batype.admin:
    description: 允许设置属性和重载
    default: op
  bamodifier.use:
    description: 允许查看属性加成
    default: true
  bamodifier.admin:
    description: 允许设置属性加成
    default: op